name: Security Scan
on: [push]

jobs:
  ZAP_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://www.zaproxy.org'
  Snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk scan for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
      - run: npm ci
  
